# Generated by Django 4.2.1 on 2023-06-02 00:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=9141)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=7)),
                ('owner', models.CharField(max_length=100)),
                ('elevation', models.DecimalField(decimal_places=2, max_digits=7)),
                ('maintenance_notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='collector_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='DischargePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=9141)),
                ('max_flow_rate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('water_quality', models.CharField(max_length=50)),
                ('permit_number', models.CharField(max_length=50)),
                ('monitoring_frequency', models.CharField(max_length=50)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='discharge_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Manhole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('depth', models.DecimalField(decimal_places=2, max_digits=5)),
                ('material', models.CharField(max_length=50)),
                ('installation_date', models.DateField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=9141)),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20)),
                ('maintenance_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='manhole_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Pipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', models.DecimalField(decimal_places=2, max_digits=5)),
                ('length', models.DecimalField(decimal_places=2, max_digits=7)),
                ('material', models.CharField(max_length=50)),
                ('installation_date', models.DateField()),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=9141)),
                ('condition', models.CharField(choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=20)),
                ('maintenance_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pipe_photos/')),
            ],
        ),
    ]
