# Generated by Django 4.2.1 on 2023-06-04 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wastewater_prishtina_app', '0002_alter_collectorpoint_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipe',
            old_name='geometry',
            new_name='location',
        ),
    ]
